import type { Metadata } from 'next';

import ReactNativeRegistry from './registry';

import './globals.css';

import { interTight } from '@/utils/style';

export const metadata: Metadata = {
	title: 'AiGO',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={interTight.className}>
				<ReactNativeRegistry>{children}</ReactNativeRegistry>
			</body>
		</html>
	);
}
