name: Eslint & Typecheck
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
      - "dev"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install yarn cli
        run: corepack enable && corepack prepare yarn@4.1.1 --activate

      - name: Set yarn version
        run: yarn set version 4.1.1

      - name: Install dependencies
        run: yarn

      - name: Execute eslint
        run: yarn lint

      - name: Execute type check with tsc
        run: yarn type-check
